---
# defaults file for setup-macos
macos_brew_pkgs: [] # List of brew packages to install

macos_brew_casks: [] # List of brew casks that would like to install

macos_brew_taps: [] # List of brew taps to install
