kubernetes_linux_modules:
  - overlay
  - br_netfilter

kubernetes_kernel_params:
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1

# List of ssh public keys that need to be added to the authorized keys file
kubernetes_authorized_keys: []
